from PIL import Image
import numpy as np
from matplotlib.pyplot import imshow

class img_converter:

    """Read in image bitmap and convert to array"""

    def __init__(self, path):
        self.path = path
        self.arr = self._read_image()

    def _read_image(self):
        """
        Read image and store it as 'arr' attribute

        """
        Image.open(self.path).save("data/bmp/img.bmp")
        img = Image.open("data/bmp/img.bmp")
        img_arr = np.array(img, dtype='int32')
        img.close()
        return img_arr

    def display_image(self):
        """
        Display image

        """
        self.arr = self.arr.astype(dtype='uint8')
        img = Image.fromarray(self.arr, 'RGB')
        imshow(np.asarray(img))

    def reshape_img(self):
        """
        Takes in array generated by read_image function and converts to long format

        """
        long_array = np.reshape(self.arr, (self.arr.shape[0] * self.arr.shape[1], self.arr.shape[2]))
        self.long_array = long_array
        return long_array